@endpoint = http://localhost:3001/api/v1/albums
# @name postAlbum
###
### POST Request for a album 
## Expected result is ........
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ 
   "title": "The Dark Side of the Moon",
   "artist": "Pink Floyd",
   "rating": 5,
   "acquiredDate": "2023-10-15",
   "isBorrowed": false,
   "owner": "Elain"
}

@newObjectId = {{postAlbum.response.headers.location}}
@firstID = {{GETAllAlbums.response.body.[0]._id}}
# @name GETAllAlbums
### GET Request for all albums
## Expected result is ........
GET {{endpoint}}/{{newObjectId}} HTTP/1.1
### Another POST Request for a album
## Expected result is ........
POST {{endpoint}} HTTP/1.1
content-type: application/json
{ 
   "title": "Abbey Road",
   "artist": "The Beatles",
   "rating": 5,
   "acquiredDate": "2022-05-20",
   "isBorrowed": false,
   "owner": "Elain"
}
### PUT Request to update the album
## Expected result is ..........
PUT {{endpoint}}/{{newObjectId}} HTTP/1.1

###
DELETE {{endpoint}}/{{newObjectId}} HTTP/1.1
