###
### POST Request for a contact 
## Expected result is ........
POST http://localhost:3001/api/v1/users HTTP/1.1
content-type: application/json

{ "name" : "John Doe",
   "phonenumber" : "0871234567",
   "email": "jdoe123@gmail.com",
   "dob": "2005-03-15"}

### Another POST Request for a contact
## Expected result is ........
POST http://localhost:3001/api/v1/users HTTP/1.1
content-type: application/json

{ "name" : "Elain Polakova",
   "phonenumber" : "0871234567",
   "email": "s00250500@atu.ie",
   "dob": "1995-03-15"}